export const LOGIN_REDUCER = {
  SET_EMAIL: 'SET_EMAIL',
  SET_PASSWORD: 'SET_PASSWORD',
  SET_EMAIL_ERROR: 'SET_EMAIL_ERROR',
  SET_PASSWORD_ERROR: 'SET_PASSWORD_ERROR',
  SET_USER_DETAILS: 'SET_USER_DETAILS',
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_FAILED: 'LOGIN_FAILED'
}

export const PROJECT_REDUCER = {
  SET_PROJECTS: 'SET_PROJECTS'
}
